openapi: 3.0.2
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.19
servers:
  - url: http://localhost:8080
tags:
  - name: vehicle
    description: Everything about your vehicle
paths:
  /listings:
    get:
      tags:
        - vehicle
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
      summary: Get all data from vehicle
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
        "404":
          description: Vehicle data not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/404"
    post:
      tags: vehicle
      summary: Add new vehicle data
      parameters:
        - name: idempotency-key
          in: header
          required: true
          description: Sebuah id unique untuk mencegah duplicate request, header ini diisi dengan uuid
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - make
                - model
                - year
                - mileage
                - price
                - condition
                - transmission
                - fuel_type
                - color
                - status
                - location
              properties:
                name:
                  type: string
                make:
                  type: string
                model:
                  type: string
                year:
                  type: integer
                mileage:
                  type: string
                price:
                  type: integer
                condition:
                  type: string
                transmission:
                  type: string
                fuel_type:
                  type: string
                color:
                  type: string
                status:
                  type: string
                  enum:
                    - available
                    - sold
                    - pending
                location:
                  type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 201
                  message:
                    type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/409"
  /filters:
    get:
      tags: vehicle
      summary: Get vehicle data by fuel type
      parameters:
        - name: fuel_type
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VehicleSearch"
              examples:
                withData:
                  summary: Data found
                  value:
                    status_code: 200
                    data:
                      [
                        {
                          "vehicle_id": "vehicle id",
                          "name": "name",
                          "make": "make",
                          "model": "model",
                          "year": 0,
                          "mileage": "mileage",
                          "price": "price",
                          "condition": "condition",
                          "transmission": "transmission",
                          "fuel_type": "fuel type",
                          "color": "color",
                          "location": "location",
                          "status": "status",
                        },
                      ]
                emptyData:
                  summary: No data found
                  value:
                    status_code: 200
                    data: []
  /listings/search:
    get:
      tags: vehicle
      summary: Get vehicle data by make, fuel type, price, and year
      parameters:
        - name: make_fuel_type
          in: query
          required: false
          schema:
            type: string
        - name: price
          in: query
          required: false
          schema:
            type: integer
        - name: year
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VehicleSearch"
              examples:
                withData:
                  summary: Data found
                  value:
                    status_code: 200
                    data:
                      [
                        {
                          "vehicle_id": "vehicle id",
                          "name": "name",
                          "make": "make",
                          "model": "model",
                          "year": 0,
                          "mileage": "mileage",
                          "price": "price",
                          "condition": "condition",
                          "transmission": "transmission",
                          "fuel_type": "fuel type",
                          "color": "color",
                          "location": "location",
                          "status": "status",
                        },
                      ]
                emptyData:
                  summary: No data found
                  value:
                    status_code: 200
                    data: []
  /listings/search/suggest:
    get:
      tags: vehicle
      summary: Get vehicle data by make, fuel type, price, and year
      parameters:
        - name: parameter
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VehicleSearch"
              examples:
                withData:
                  summary: Data found
                  value:
                    status_code: 200
                    data:
                      [
                        {
                          "vehicle_id": "vehicle id",
                          "name": "name",
                          "make": "make",
                          "model": "model",
                          "year": 0,
                          "mileage": "mileage",
                          "price": "price",
                          "condition": "condition",
                          "transmission": "transmission",
                          "fuel_type": "fuel type",
                          "color": "color",
                          "location": "location",
                          "status": "status",
                        },
                      ]
                emptyData:
                  summary: No data found
                  value:
                    status_code: 200
                    data: []
  /listings/{vehicle_id}:
    get:
      tags: vehicle
      summary: Get vehicle data by vehicle id
      parameters:
        - name: vehicle_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SingleVehicle"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/404"
    patch:
      tags: vehicle
      summary: Update vehicle data
      parameters:
        - name: vehicle_id
          in: path
          required: true
          description: Id data yang ingin diupdate
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                make:
                  type: string
                model:
                  type: string
                year:
                  type: integer
                mileage:
                  type: string
                price:
                  type: integer
                condition:
                  type: string
                transmission:
                  type: string
                fuel_type:
                  type: string
                color:
                  type: string
                status:
                  type: string
                  enum:
                    - available
                    - sold
                    - pending
                location:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success updated vehicle data
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/404"
    delete:
      tags: vehicle
      summary: Delete vehicle data
      parameters:
        - name: vehicle_id
          in: path
          required: true
          description: Id data yang ingin diupdate
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/404"
components:
  schemas:
    Vehicle:
      type: object
      properties:
        status_code:
          type: integer
        page:
          type: integer
        total_data:
          type: integer
        total_page:
          type: integer
        data:
          type: array
          items:
            type: object
            properties:
              vehicle_id:
                type: string
              name:
                type: string
              make:
                type: string
              model:
                type: string
              year:
                type: integer
              mileage:
                type: string
              price:
                type: integer
              condition:
                type: string
              transmission:
                type: string
              fuel_type:
                type: string
              color:
                type: string
              location:
                type: string
              status:
                type: string
    VehicleSearch:
      type: object
      properties:
        status_code:
          type: integer
          example: 200
        data:
          type: array
          items:
            type: object
            properties:
              vehicle_id:
                type: string
              name:
                type: string
              make:
                type: string
              model:
                type: string
              year:
                type: integer
              mileage:
                type: string
              price:
                type: string
              condition:
                type: string
              transmission:
                type: string
              fuel_type:
                type: string
              color:
                type: string
              location:
                type: string
              status:
                type: string
    SingleVehicle:
      type: object
      properties:
        status_code:
          type: integer
          example: 200
        data:
          type: object
          properties:
            vehicle_id:
              type: string
            name:
              type: string
            make:
              type: string
            model:
              type: string
            year:
              type: integer
            mileage:
              type: string
            price:
              type: string
            condition:
              type: string
            transmission:
              type: string
            fuel_type:
              type: string
            color:
              type: string
            location:
              type: string
            status:
              type: string
    400:
      type: object
      properties:
        status_code:
          type: integer
          example: 400
        error:
          type: string
    404:
      type: object
      properties:
        status_code:
          type: integer
          example: 404
        error:
          type: string
    409:
      type: object
      properties:
        status_code:
          type: integer
          example: 409
        error:
          type: string
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
